image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

# Build Stage Instructions for develop and all feature branches
build:
  stage: build
  tags:
    - grad
  script: ./gradlew --build-cache assemble
  only:
  - develop
  - /^feature_.*$/
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

# Test Stage Instructions for develop and all feature branches
test:
  stage: test
  tags:
    - grad
  script: ./gradlew check
  only:
  - develop
  - /^feature_.*$/
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

# Deployment Instructions only for *develop* branch
deploy:
    stage: deploy
    tags:
    - dalfcs_gitlab_docker_ci
    image: ruby:2.3
    script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$API_KEY
    only:
    - master
